x   <- strsplit(as.character(test$col), ";\\s?") # split the strings
lvl <- unique(unlist(x))                         # get unique elements
x   <- lapply(x, factor, levels = lvl)           # convert to factor
t(sapply(x, table))                              # count elements and transpose

raw$cert_Admin<-ifelse("Admin" %in% raw[,"Certifications"], 1,0)
raw$cert_AdvAdmin<-ifelse("Advanced Admin" %in% raw[,"Certifications"], 1,0)
raw$cert_PlatDev1<-ifelse("Platform Developer I" %in% raw[,"Certifications"], 1,0)
raw$cert_PlatAppBuild<-ifelse("Platform App Builder" %in% raw[,"Certifications"], 1,0)
raw$cert_ComCloudCon<-ifelse("Community Cloud Consultant" %in% raw[,"Certifications"], 1,0)
raw$cert_TA<-ifelse("Certified Technical Architect" %in% raw[,"Certifications"], 1,0)
raw$cert_Pardot<-ifelse("Pardot Consultant" %in% raw[,"Certifications"], 1,0)
raw$cert_SalesCC<-ifelse("Sales Cloud Consultant" %in% raw[,"Certifications"], 1,0)
raw$cert_ServiceCC<-ifelse("Service Cloud Consultant" %in% raw[,"Certifications"], 1,0)
raw$cert_mktCon<-ifelse("Marketing Cloud Consultant" %in% raw[,"Certifications"], 1,0)
raw$cert_PlatDev2<-ifelse("Platform Developer II" %in% raw[,"Certifications"], 1,0)
raw$cert_dev501<-ifelse("DEV501" %in% raw[,"Certifications"], 1,0)
raw$cust_type_consult_part<-ifelse("Consulting Partner" %in% raw[,"customer_type"], 1,0)
raw$cust_type_ISV<-ifelse("ISV" %in% raw[,"customer_type"], 1,0)
raw$cust_type_cust<-ifelse("Customer" %in% raw[,"customer_type"], 1,0)
raw$skills_admin<-ifelse("Admin" %in% raw[,"skills"], 1,0)
raw$skills_ent_proj<-ifelse("Enterprise Projects" %in% raw[,"skills"], 1,0)
raw$skills_integ<-ifelse("Integrations" %in% raw[,"skills"], 1,0)
raw$skills_dig_mkt<-ifelse("Digital Marketing" %in% raw[,"skills"], 1,0)
raw$skills_analytics<-ifelse("Analytics" %in% raw[,"skills"], 1,0)
raw$skills_demand_gen<-ifelse("Demand Generation" %in% raw[,"skills"], 1,0)
raw$skills_apex<-ifelse("Apex" %in% raw[,"skills"], 1,0)
raw$skills_training<-ifelse("Training" %in% raw[,"skills"], 1,0)
raw$skills_agile<-ifelse("Agile" %in% raw[,"skills"], 1,0)
raw$skills_dot_net<-ifelse(".NET" %in% raw[,"skills"], 1,0)
raw$skills_b2b<-ifelse("B2B" %in% raw[,"skills"], 1,0)
raw$skills_config<-ifelse("Configuration" %in% raw[,"skills"], 1,0)
raw$skills_lead_gen<-ifelse("Lead Generation" %in% raw[,"skills"], 1,0)
raw$skills_arch<-ifelse("Architecture" %in% raw[,"skills"], 1,0)
raw$skills_proj_mgmt<-ifelse("Project Management" %in% raw[,"skills"], 1,0)
raw$skills_qa<-ifelse("QA" %in% raw[,"skills"], 1,0)
raw$skills_dba<-ifelse("DBA" %in% raw[,"skills"], 1,0)
raw$skills_erp<-ifelse("ERP" %in% raw[,"skills"], 1,0)
raw$skills_soc<-ifelse("Social" %in% raw[,"skills"], 1,0)
raw$skills_excel<-ifelse("Excel" %in% raw[,"skills"], 1,0)
raw$skills_java<-ifelse("Java" %in% raw[,"skills"], 1,0)
raw$skills_scrum<-ifelse("Scrum" %in% raw[,"skills"], 1,0)
raw$skills_visualforce<-ifelse("Visualforce" %in% raw[,"skills"], 1,0)
raw$skills_c_sharp<-ifelse("C#" %in% raw[,"skills"], 1,0)
raw$skills_b2c<-ifelse("B2C" %in% raw[,"skills"], 1,0)
raw$skills_css<-ifelse("CSS" %in% raw[,"skills"], 1,0)
raw$skills_cng_mgmt<-ifelse("Change Management" %in% raw[,"skills"], 1,0)
raw$skills_prod_dev<-ifelse("Product Development" %in% raw[,"skills"], 1,0)
raw$skills_heroku<-ifelse("Heroku" %in% raw[,"skills"], 1,0)
raw$skills_dir_rpts<-ifelse("Direct Reports" %in% raw[,"skills"], 1,0)
raw$skills_content<-ifelse("Content" %in% raw[,"skills"], 1,0)
raw$skills_email_mkt<-ifelse("Email Marketing" %in% raw[,"skills"], 1,0)
raw$skills_angular<-ifelse("Angular" %in% raw[,"skills"], 1,0)
raw$skills_ux_ui<-ifelse("UX/UI" %in% raw[,"skills"], 1,0)
raw$skills_sem<-ifelse("Paid Advertising" %in% raw[,"skills"], 1,0)
raw$skills_sql<-ifelse("SQL" %in% raw[,"skills"], 1,0)
raw$skills_mobile<-ifelse("Mobile" %in% raw[,"skills"], 1,0)
raw$skills_html<-ifelse("HTML" %in% raw[,"skills"], 1,0)
raw$skills_cpq<-ifelse("CPQ" %in% raw[,"skills"], 1,0)
raw$skills_hcm<-ifelse("HCM" %in% raw[,"skills"], 1,0)
raw$skills_prod_mkt<-ifelse("Product Marketing" %in% raw[,"skills"], 1,0)
raw$skills_waterfall<-ifelse("Waterfall" %in% raw[,"skills"], 1,0)
raw$skills_grow_mkt<-ifelse("Growth Marketing" %in% raw[,"skills"], 1,0)
raw$skills_rete_mkt<-ifelse("Retention Marketing" %in% raw[,"skills"], 1,0)
raw$skills_js<-ifelse("JavaScript" %in% raw[,"skills"], 1,0)
raw$skills_py<-ifelse("Python" %in% raw[,"skills"], 1,0)
raw$skills_sem<-ifelse("SOE/SEM" %in% raw[,"skills"], 1,0)
raw$sfdc_prod_sales_cld<-ifelse("Sales Cloud" %in% raw[,"SFDC_prod"], 1,0)
raw$sfdc_prod_mkt_cld<-ifelse("Marketing Cloud" %in% raw[,"SFDC_prod"], 1,0)
raw$sfdc_prod_cpq_cld<-ifelse("CPQ Cloud" %in% raw[,"SFDC_prod"], 1,0)
raw$sfdc_prod_cust_comm<-ifelse("Customer Communities" %in% raw[,"SFDC_prod"], 1,0)
raw$sfdc_prod_data_com<-ifelse("Data.com" %in% raw[,"SFDC_prod"], 1,0)
raw$sfdc_prod_serv_cld<-ifelse("Service Cloud" %in% raw[,"SFDC_prod"], 1,0)
raw$sfdc_prod_emp_comms<-ifelse("Employee Communities" %in% raw[,"SFDC_prod"], 1,0)
raw$sfdc_prod_part_comms<-ifelse("Partner Communities" %in% raw[,"SFDC_prod"], 1,0)
raw$bckgrd_admin<-ifelse("Administrator" %in% raw[,"background"], 1,0)
raw$bckgrd_alliances<-ifelse("Alliances" %in% raw[,"background"], 1,0)
raw$bckgrd_ba<-ifelse("Business Analyst" %in% raw[,"background"], 1,0)
raw$bckgrd_bd<-ifelse("Business Development" %in% raw[,"background"], 1,0)
raw$bckgrd_prod_own<-ifelse("Product Owner" %in% raw[,"background"], 1,0)
raw$bckgrd_mkt_mgr<-ifelse("Marketing Manager/Director" %in% raw[,"background"], 1,0)
raw$bckgrd_vp<-ifelse("VP" %in% raw[,"background"], 1,0)
raw$bckgrd_it_mgr<-ifelse("IT Manager/Director" %in% raw[,"background"], 1,0)
raw$bckgrd_mkt_auto<-ifelse("Marketing Automation" %in% raw[,"background"], 1,0)
raw$bckgrd_sa<-ifelse("Solution Architect" %in% raw[,"background"], 1,0)
raw$bckgrd_dev<-ifelse("Developer" %in% raw[,"background"], 1,0)
raw$bckgrd_proj_mgr<-ifelse("Project Manager" %in% raw[,"background"], 1,0)
raw$bckgrd_prod_mgr<-ifelse("Product Manager" %in% raw[,"background"], 1,0)
raw$bckgrd_sales_ops<-ifelse("Sales Operations" %in% raw[,"background"], 1,0)
raw$bckgrd_ta<-ifelse("Technical Architect" %in% raw[,"background"], 1,0)
raw$bckgrd_sales_mgmt<-ifelse("Sales Management" %in% raw[,"background"], 1,0)
raw$bckgrd_dev_mgr<-ifelse("Development Manager" %in% raw[,"background"], 1,0)
raw$bckgrd_cmo<-ifelse("CMO" %in% raw[,"background"], 1,0)
raw$bckgrd_mkt_ops<-ifelse("Marketing Operations" %in% raw[,"background"], 1,0)
raw$bckgrd_mkt_spec<-ifelse("Marketing Specialist" %in% raw[,"background"], 1,0)
raw$bckgrd_client<-ifelse("N/A Client" %in% raw[,"background"], 1,0)
raw$bckgrd_sr_apt<-ifelse("Senior Appointment" %in% raw[,"background"], 1,0)
raw$bckgrd_sales<-ifelse("Sales and BD" %in% raw[,"background"], 1,0)
raw$bckgrd_pre_sales<-ifelse("Pre-sales" %in% raw[,"background"], 1,0)
raw$bckgrd_prac_ldr<-ifelse("Practice Leadership" %in% raw[,"background"], 1,0)
raw$bckgrd_cro<-ifelse("CRO" %in% raw[,"background"], 1,0)
raw$bckgrd_ent_app<-ifelse("Enterprise Applications" %in% raw[,"background"], 1,0)
raw$bckgrd_pgm_mgr<-ifelse("Program Manager" %in% raw[,"background"], 1,0)
raw$bckgrd_sales_enable<-ifelse("Sales Enablement" %in% raw[,"background"], 1,0)
raw$bckgrd_qa<-ifelse("QA" %in% raw[,"background"], 1,0)
raw$bckgrd_sales_eng<-ifelse("Sales Engineer" %in% raw[,"background"], 1,0)
raw$bckgrd_mkt_consult<-ifelse("Marketing Consultation" %in% raw[,"background"], 1,0)
raw$bckgrd_integ_arch<-ifelse("Integration Architect" %in% raw[,"background"], 1,0)
raw$bckgrd_ae<-ifelse("Account Executive" %in% raw[,"background"], 1,0)
raw$bckgrd_engage_mgr<-ifelse("Engagement Manger" %in% raw[,"background"], 1,0)
raw$bckgrd_serv_ops<-ifelse("Service Operations" %in% raw[,"background"], 1,0)