print("Sinking output text")
sink("output.txt", append=TRUE, split=TRUE)

# Hi friend - R Lessons

raw <- read.csv("salarydata6_20.csv")
ifelse('Admin' %in% raw[,'Certifications'], raw$cert_Admin=1, raw$cert_Admin=0)
ifelse('Advanced Admin' %in% raw[,'Certifications'], raw$cert_AdvAdmin=1, raw$cert_AdvAdmin=0)
ifelse('Platform Developer I' %in% raw[,'Certifications'], raw$cert_PlatDev1=1, raw$cert_PlatDev1=0)
ifelse('Platform App Builder' %in% raw[,'Certifications'], raw$cert_PlatAppBuild=1, raw$cert_PlatAppBuild=0)
ifelse('Community Cloud Consultant' %in% raw[,'Certifications'], raw$cert_ComCloudCon=1, raw$cert_ComCloudCon=0)
ifelse('Certified Technical Architect' %in% raw[,'Certifications'], raw$cert_TA=1, raw$cert_TA=0)
ifelse('Pardot Consultant' %in% raw[,'Certifications'], raw$cert_Pardot=1, raw$cert_Pardot=0)
ifelse('Sales Cloud Consultant' %in% raw[,'Certifications'], raw$cert_SalesCC=1, raw$cert_SalesCC=0)
ifelse('Service Cloud Consultant' %in% raw[,'Certifications'], raw$cert_ServiceCC=1, raw$cert_ServiceCC=0)
ifelse('Marketing Cloud Consultant' %in% raw[,'Certifications'], raw$cert_mktCon=1, raw$cert_mktCon=0)
ifelse('Platform Developer II' %in% raw[,'Certifications'], raw$cert_PlatDev2=1, raw$cert_PlatDev2=0)
ifelse('DEV501' %in% raw[,'Certifications'], raw$cert_dev501=1, raw$cert_dev501=0)
ifelse('Consulting Partner' %in% raw[,'customer_type'], raw$cust_type_consult_part=1, raw$cust_type_consult_part=0)
ifelse('ISV' %in% raw[,'customer_type'], raw$cust_type_ISV=1, raw$cust_type_ISV=0)
ifelse('Customer' %in% raw[,'customer_type'], raw$cust_type_cust=1, raw$cust_type_cust=0)
ifelse('Admin' %in% raw[,'Certifications'], raw$Admin=1, raw$Admin=0)
ifelse('Enterprise Projects' %in% raw[,'skills'], raw$skills_ent_proj=1, raw$skills_ent_proj=0)
ifelse('Integrations' %in% raw[,'skills'], raw$skills_integ=1, raw$skills_integ=0)
ifelse('Digital Marketing' %in% raw[,'skills'], raw$skills_dig_mkt=1, raw$skills_dig_mkt=0)
ifelse('Analytics' %in% raw[,'skills'], raw$skills_analytics=1, raw$skills_analytics=0)
ifelse('Demand Generation' %in% raw[,'skills'], raw$skills_demand_gen=1, raw$skills_demand_gen=0)
ifelse('Apex' %in% raw[,'skills'], raw$skills_apex=1, raw$skills_apex=0)
ifelse('Training' %in% raw[,'skills'], raw$skills_training=1, raw$skills_training=0)
ifelse('Agile' %in% raw[,'skills'], raw$skills_agile=1, raw$skills_agile=0)
ifelse('.NET' %in% raw[,'skills'], raw$skills_dot_net=1, raw$skills_dot_net=0)
ifelse('B2B' %in% raw[,'skills'], raw$skills_b2b=1, raw$skills_b2b=0)
ifelse('Configuration' %in% raw[,'skills'], raw$skills_config=1, raw$skills_config=0)
ifelse('Lead Generation' %in% raw[,'skills'], raw$skills_lead_gen=1, raw$skills_lead_gen=0)
ifelse('Architecture' %in% raw[,'skills'], raw$skills_arch=1, raw$skills_arch=0)
ifelse('Project Management' %in% raw[,'skills'], raw$skills_proj_mgmt=1, raw$skills_proj_mgmt=0)
ifelse('QA' %in% raw[,'skills'], raw$skills_qa=1, raw$skills_qa=0)
ifelse('DBA' %in% raw[,'skills'], raw$skills_dba=1, raw$skills_dba=0)
ifelse('ERP' %in% raw[,'skills'], raw$skills_erp=1, raw$skills_erp=0)
ifelse('Social' %in% raw[,'skills'], raw$skills_soc=1, raw$skills_soc=0)
ifelse('Excel' %in% raw[,'skills'], raw$skills_excel=1, raw$skills_excel=0)
ifelse('Java' %in% raw[,'skills'], raw$skills_java=1, raw$skills_java=0)
ifelse('Scrum' %in% raw[,'skills'], raw$skills_scrum=1, raw$skills_scrum=0)
ifelse('Visualforce' %in% raw[,'skills'], raw$skills_visualforce=1, raw$skills_visualforce=0)
ifelse('C#' %in% raw[,'skills'], raw$skills_c_sharp=1, raw$skills_c_sharp=0)
ifelse('B2C' %in% raw[,'skills'], raw$skills_b2c=1, raw$skills_b2c=0)
ifelse('CSS' %in% raw[,'skills'], raw$skills_css=1, raw$skills_css=0)
ifelse('Change Management' %in% raw[,'skills'], raw$skills_cng_mgmt=1, raw$skills_cng_mgmt=0)
ifelse('Product Development' %in% raw[,'skills'], raw$skills_prod_dev=1, raw$skills_prod_dev=0)
ifelse('Heroku' %in% raw[,'skills'], raw$skills_heroku=1, raw$skills_heroku=0)
ifelse('Direct Reports' %in% raw[,'skills'], raw$skills_dir_rpts=1, raw$skills_dir_rpts=0)
ifelse('Content' %in% raw[,'skills'], raw$skills_content=1, raw$skills_content=0)
ifelse('Email Marketing' %in% raw[,'skills'], raw$skills_email_mkt=1, raw$skills_email_mkt=0)
ifelse('Angular' %in% raw[,'skills'], raw$skills_angular=1, raw$skills_angular=0)
ifelse('UX/UI' %in% raw[,'skills'], raw$skills_ux_ui=1, raw$skills_ux_ui=0)
ifelse('Paid Advertising' %in% raw[,'skills'], raw$skills_sem=1, raw$skills_sem=0)
ifelse('SQL' %in% raw[,'skills'], raw$skills_sql=1, raw$skills_sql=0)
ifelse('Mobile' %in% raw[,'skills'], raw$skills_mobile=1, raw$skills_mobile=0)
ifelse('HTML' %in% raw[,'skills'], raw$skills_html=1, raw$skills_html=0)
ifelse('CPQ' %in% raw[,'skills'], raw$skills_cpq=1, raw$skills_cpq=0)
ifelse('HCM' %in% raw[,'skills'], raw$skills_hcm=1, raw$skills_hcm=0)
ifelse('Product Marketing' %in% raw[,'skills'], raw$skills_prod_mkt=1, raw$skills_prod_mkt=0)
ifelse('Waterfall' %in% raw[,'skills'], raw$skills_waterfall=1, raw$skills_waterfall=0)
ifelse('Growth Marketing' %in% raw[,'skills'], raw$skills_grow_mkt=1, raw$skills_grow_mkt=0)
ifelse('Retention Marketing' %in% raw[,'skills'], raw$skills_rete_mkt=1, raw$skills_rete_mkt=0)
ifelse('JavaScript' %in% raw[,'skills'], raw$skills_js=1, raw$skills_js=0)
ifelse('Python' %in% raw[,'skills'], raw$skills_py=1, raw$skills_py=0)
ifelse('SOE/SEM' %in% raw[,'skills'], raw$skills_sem=1, raw$skills_sem=0)
ifelse('Sales Cloud' %in% raw[,'SFDC_prod'], raw$sfdc_prod_sales_cld=1, raw$sfdc_prod_sales_cld=0)
ifelse('Marketing Cloud' %in% raw[,'SFDC_prod'], raw$sfdc_prod_mkt_cld=1, raw$sfdc_prod_mkt_cld=0)
ifelse('CPQ Cloud' %in% raw[,'SFDC_prod'], raw$sfdc_prod_cpq_cld=1, raw$sfdc_prod_cpq_cld=0)
ifelse('Customer Communities' %in% raw[,'SFDC_prod'], raw$sfdc_prod_cust_comm=1, raw$sfdc_prod_cust_comm=0)
ifelse('Data.com' %in% raw[,'SFDC_prod'], raw$sfdc_prod_data_com=1, raw$sfdc_prod_data_com=0)
ifelse('Service Cloud' %in% raw[,'SFDC_prod'], raw$sfdc_prod_serv_cld=1, raw$sfdc_prod_serv_cld=0)
ifelse('Employee Communities' %in% raw[,'SFDC_prod'], raw$sfdc_prod_emp_comms=1, raw$sfdc_prod_emp_comms=0)
ifelse('Partner Communities' %in% raw[,'SFDC_prod'], raw$sfdc_prod_part_comms=1, raw$sfdc_prod_part_comms=0)
ifelse('Administrator' %in% raw[,'background'], raw$bckgrd_admin=1, raw$bckgrd_admin=0)
ifelse('Alliances' %in% raw[,'background'], raw$bckgrd_alliances=1, raw$bckgrd_alliances=0)
ifelse('Business Analyst' %in% raw[,'background'], raw$bckgrd_ba=1, raw$bckgrd_ba=0)
ifelse('Business Development' %in% raw[,'background'], raw$bckgrd_bd=1, raw$bckgrd_bd=0)
ifelse('Product Owner' %in% raw[,'background'], raw$bckgrd_prod_own=1, raw$bckgrd_prod_own=0)
ifelse('Marketing Manager/Director' %in% raw[,'background'], raw$bckgrd_mkt_mgr=1, raw$bckgrd_mkt_mgr=0)
ifelse('VP' %in% raw[,'background'], raw$bckgrd_vp=1, raw$bckgrd_vp=0)
ifelse('IT Manager/Director' %in% raw[,'background'], raw$bckgrd_it_mgr=1, raw$bckgrd_it_mgr=0)
ifelse('Marketing Automation' %in% raw[,'background'], raw$bckgrd_mkt_auto=1, raw$bckgrd_mkt_auto=0)
ifelse('Solution Architect' %in% raw[,'background'], raw$bckgrd_sa=1, raw$bckgrd_sa=0)
ifelse('Developer' %in% raw[,'background'], raw$bckgrd_dev=1, raw$bckgrd_dev=0)
ifelse('Project Manager' %in% raw[,'background'], raw$bckgrd_proj_mgr=1, raw$bckgrd_proj_mgr=0)
ifelse('Product Manager' %in% raw[,'background'], raw$bckgrd_prod_mgr=1, raw$bckgrd_prod_mgr=0)
ifelse('Sales Operations' %in% raw[,'background'], raw$bckgrd_sales_ops=1, raw$bckgrd_sales_ops=0)
ifelse('Technical Architect' %in% raw[,'background'], raw$bckgrd_ta=1, raw$bckgrd_ta=0)
ifelse('Sales Management' %in% raw[,'background'], raw$bckgrd_sales_mgmt=1, raw$bckgrd_sales_mgmt=0)
ifelse('Development Manager' %in% raw[,'background'], raw$bckgrd_dev_mgr=1, raw$bckgrd_dev_mgr=0)
ifelse('CMO' %in% raw[,'background'], raw$bckgrd_cmo=1, raw$bckgrd_cmo=0)
ifelse('Marketing Operations' %in% raw[,'background'], raw$bckgrd_mkt_ops=1, raw$bckgrd_mkt_ops=0)
ifelse('Marketing Specialist' %in% raw[,'background'], raw$bckgrd_mkt_spec=1, raw$bckgrd_mkt_spec=0)
ifelse('N/A Client' %in% raw[,'background'], raw$bckgrd_client=1, raw$bckgrd_client=0)
ifelse('Senior Appointment' %in% raw[,'background'], raw$bckgrd_sr_apt=1, raw$bckgrd_sr_apt=0)
ifelse('Sales and BD' %in% raw[,'background'], raw$bckgrd_sales=1, raw$bckgrd_sales=0)
ifelse('Pre-sales' %in% raw[,'background'], raw$bckgrd_pre_sales=1, raw$bckgrd_pre_sales=0)
ifelse('Practice Leadership' %in% raw[,'background'], raw$bckgrd_prac_ldr=1, raw$bckgrd_prac_ldr=0)
ifelse('CRO' %in% raw[,'background'], raw$bckgrd_cro=1, raw$bckgrd_cro=0)
ifelse('Enterprise Applications' %in% raw[,'background'], raw$bckgrd_ent_app=1, raw$bckgrd_ent_app=0)
ifelse('Program Manager' %in% raw[,'background'], raw$bckgrd_pgm_mgr=1, raw$bckgrd_pgm_mgr=0)
ifelse('Sales Enablement' %in% raw[,'background'], raw$bckgrd_sales_enable=1, raw$bckgrd_sales_enable=0)
ifelse('QA' %in% raw[,'background'], raw$bckgrd_qa=1, raw$bckgrd_qa=0)
ifelse('Sales Engineer' %in% raw[,'background'], raw$bckgrd_sales_eng=1, raw$bckgrd_sales_eng=0)
ifelse('Marketing Consultation' %in% raw[,'background'], raw$bckgrd_mkt_consult=1, raw$bckgrd_mkt_consult=0)
ifelse('Integration Architect' %in% raw[,'background'], raw$bckgrd_integ_arch=1, raw$bckgrd_integ_arch=0)
ifelse('Account Executive' %in% raw[,'background'], raw$bckgrd_ae=1, raw$bckgrd_ae=0)
ifelse('Engagement Manger' %in% raw[,'background'], raw$bckgrd_engage_mgr=1, raw$bckgrd_engage_mgr=0)
ifelse('Service Operations' %in% raw[,'background'], raw$bckgrd_serv_ops=1, raw$bckgrd_serv_ops=0)

    # after dt is converted, do analysis
    
model <- lm(Salary~Gender,data=raw)

summary(model)